version: '1.0'
services:
  node:
    image: "node:8"
    user: "node"

steps:
  test_all_the_code:
    image: node:5
    working_directory: ${{main_clone}}
    commands:
      - node --version
      - npm install -g npm@latest
      - npm install
      - npm test
